### ISSUE TITLE
Iterable made from an iterator can still only be iterated once

### ISSUE THREAD

**Issue by RebeccaStevens** [vitaly-t/iter-ops#101] opened 2021-12-29 12:19 UTC
I've just noticed another potential issue.

The iterable made from an iterator with this part of the code:

https://github.com/vitaly-t/iter-ops/blob/ccebb8e4530bc4de9a01f0143f86b534aba2e115/src/helpers.ts#L122-L143

would only be iterable once. As once the original iterator has been exhausted; any new iterator created from the iterable will also be exhausted.

If this function only internally used it wouldn't be an issue as it can be guaranteed that the iterable is never iterated more than once. But if that is the case; there could be performance gains if instead the iterator was just used directly.

**Comment by vitaly-t** [comment] 2021-12-29 12:25
The purpose of `toIterable` is to provide full type compatibility, so the pipeline can be type-casted correctly. It is not meant to create new iteration logic, because it is not even possible.

Think of promises, for example, a promise can only resolve once, and produce one value, once, that's it. The same for iterators, they cannot be iterated more than once, and we wrap them for compatibility reasons.

In all, there is no issue here, it is also by design ;)

**Comment by RebeccaStevens** [comment] 2021-12-29 12:28
I'll leave that function alone for now and focus else where. Maybe once I'm more familiar with the codebase; that function's purpose will click better for me.

**Comment by vitaly-t** [comment] 2022-09-28 21:46
@RebeccaStevens If you get a chance to review this again, I think perhaps we can close it. I don't think there is any issue here, it works as expected.

**Comment by vitaly-t** [comment] 2022-10-13 06:02
I'm closing this. There is no issue here. And iterator can be iterated only once. So when you create a new iterable from an iterator, it can also be iterated only once.

**Closed by vitaly-t** 2022-10-13 06:02 UTC
Labels: feedback wanted
