### ISSUE TITLE
Timing issue in tests

### ISSUE THREAD

**Issue by RebeccaStevens** [vitaly-t/iter-ops#243] opened 2024-08-04 14:23 UTC
https://github.com/vitaly-t/iter-ops/blob/52fb2b42f285111947f1e63bfa41fefe9808f8c7/test/ops/on-end/sync.ts#L37

This is only zero when things are really fast and it essentially rounds down zero. Some times we get `1` instead when things are a little slower.

**Comment by RebeccaStevens** [comment] 2024-08-04 14:24
https://github.com/vitaly-t/iter-ops/blob/52fb2b42f285111947f1e63bfa41fefe9808f8c7/src/ops/on-end.ts#L150

**Comment by vitaly-t** [comment] 2024-08-04 16:18
This now seems to be no longer an issue, or at least one difficult to reproduce in a local environment, so closing it.

**Closed by vitaly-t** 2024-08-04 16:18 UTC
